apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: pgdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      securityContext:
        runAsUser: 5050
        runAsGroup: 5050
        fsGroup: 5050
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/lib/pgadmin/storage && chown -R 5050:5050 /var/lib/pgadmin/storage && chmod -R 755 /var/lib/pgadmin/storage']
        volumeMounts:
        - name: pgadmin-storage
          mountPath: /var/lib/pgadmin/storage
        securityContext:
          runAsUser: 0
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest # Or a specific version
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@example.com # Replace with your desired email
        - name: PGADMIN_DEFAULT_PASSWORD
          value: password123 # Replace with a STRONG, unique password
        - name: PGADMIN_CONFIG_SERVER_MODE # Important for connecting to external DB
          value: "True"
        resources: # Optional resource limits and requests
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"

        volumeMounts:
        - name: data-files
          mountPath: /var/lib/pgadmin/data_files
          readOnly: true
        - name: medium1-files
          mountPath: /var/lib/pgadmin/medium1
          readOnly: true
        - name: pgadmin-storage
          mountPath: /var/lib/pgadmin/storage
      volumes:
      - name: data-files
        persistentVolumeClaim:
          claimName: data-files-pvc
      - name: medium1-files
        persistentVolumeClaim:
          claimName: medium1-files-pvc
      - name: pgadmin-storage
        persistentVolumeClaim:
          claimName: pgadmin-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: pgdb
spec:
  selector:
    app: pgadmin
  ports:
  - protocol: TCP
    port: 80 # Port exposed by the service
    targetPort: 80 # Port the container is listening on
    nodePort: 30001
  type: NodePort # Use LoadBalancer if you want external access in minikube
  # type: ClusterIP # Use ClusterIP if you only want internal access within the cluster