version: '3.7'
services:
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgagmin
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes: 
      - ./:/tmp/data_files