version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demodb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes: 
      - ./database:/var/lib/postgresql/data
      - ./medium1:/tmp/scripts
      - ./data_files:/tmp/data_files
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgagmin
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes: 
      - ./data_files:/tmp/data_files