version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demodb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes: 
      - ./database:/var/lib/postgresql/data
      - ./medium1:/tmp/scripts