site_name: DataBase playground with CDC 
repo_url: https://github.com/jbcodeforce/db-play
nav:
  - Postgres: postgres.md
  - MySQL: mysql.md 
  - Couchdb / Cloudand: couchdb.md
  - Mongo: mongodb.md
  - DB2: db2.md
theme: 
  name: gitbook