site_name: DataBase playground with CDC 
repo_url: https://github.com/jbcodeforce/db-play
nav:
  - introduction: index.md
  - Postgres: postgres.md
  - Cassandra: cassandra/readme.md
  - MySQL: mysql.md 
  - Couchdb / Cloudand: couchdb.md
  - Mongo: mongodb.md
  - DB2: db2.md
  - Return to main: https://jbcodeforce.github.io
  
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences