site_name: DataBase playground
repo_url: https://github.com/jbcodeforce/db-play
nav:
  - Introduction: index.md
  - SQL: sql.md
  - PostgreSQL: postgres.md
  - Cassandra: cassandra/readme.md
  - MySQL: mysql.md 
  - Couchdb / Cloudant: couchdb.md
  - Mongo: mongodb.md
  - DB2: db2.md
  - Data architecture: https://jbcodeforce.github.io/data/
  - Return to main: https://jbcodeforce.github.io
  
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences