
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgrespwd
      - POSTGRES_DB=app
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./data/appdb:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgagmin
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes: 
      - ./:/tmp/data_files