apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: postgres
  name: postgres-sa
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres
  name: postgres
spec:
  ports:
  - name: http
    port: 5432
    targetPort: 5432
  selector:
    app: postgres  
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
    storageClassName: ibmc-block-gold
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'docker.io/postgres:11.6-alpine'
          envFrom:
          - secretRef:
              name: postgres-secrets
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          resources: {}
          ports:
          - containerPort: 5432
            protocol: TCP
          securityContext:
            capabilities: {}
            privileged: false
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: postgres-data
          
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccount: postgres-sa
      schedulerName: default-scheduler
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
